meta_product_name: "Uniqueness"
meta_title: "Uniqueness - Digital gallery"
meta_description: "Designed for the rapidly growing digital art community, Uniqueness uses an intelligent algorithm to breakdown image colour complexity, helping artists to price and measure the popularity of their work."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
